name: Auto re-run (full) on failure

on:
  workflow_run:
    workflows:
      - Fetch and Commit WHOISDS NRD Data
    types:
      - completed

permissions:
  actions: write
  contents: read

env:
  # Total allowed attempts for a single run (original = 1)
  MAX_ATTEMPTS: "2"
  # Delay before triggering the re-run (seconds)
  BACKOFF_SECONDS: "360"

jobs:
  rerun-full-on-failure:
    # Job-level IF cannot use 'env', so only check the failure here.
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Show context
        run: |
          echo "Target workflow:    ${{ github.event.workflow_run.name }}"
          echo "Failed run ID:      ${{ github.event.workflow_run.id }}"
          echo "Attempt number:     ${{ github.event.workflow_run.run_attempt }}"
          echo "Conclusion:         ${{ github.event.workflow_run.conclusion }}"
          echo "Max attempts:       ${MAX_ATTEMPTS}"
          echo "Backoff (seconds):  ${BACKOFF_SECONDS}"

      # Only proceed with backoff + rerun if we are still below MAX_ATTEMPTS
      - name: Optional backoff
        if: ${{ github.event.workflow_run.run_attempt < fromJSON(env.MAX_ATTEMPTS) && env.BACKOFF_SECONDS != '0' }}
        run: sleep "${BACKOFF_SECONDS}"

      - name: Re-run entire workflow run via API
        if: ${{ github.event.workflow_run.run_attempt < fromJSON(env.MAX_ATTEMPTS) }}
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = context.payload.workflow_run.id;
            const { owner, repo } = context.repo;

            // POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun
            await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
              owner, repo, run_id
            });
            core.info(`Triggered full re-run for run ${run_id}.`);

      - name: Skipped because max attempts reached
        if: ${{ github.event.workflow_run.run_attempt >= fromJSON(env.MAX_ATTEMPTS) }}
        run: |
          echo "No auto retry: run_attempt (${{ github.event.workflow_run.run_attempt }}) >= MAX_ATTEMPTS (${MAX_ATTEMPTS})"
