name: Auto re-run (full) on failure

on:
  workflow_run:
    # List the exact workflow display names you want to auto-retry
    workflows:
      - Fetch and Commit WHOISDS NRD Data
    types:
      - completed

permissions:
  actions: write     # required to call the re-run API
  contents: read

env:
  # Maximum total attempts for a single run (original counts as attempt 1).
  # Example: 2 = allow one automatic full re-run.
  MAX_ATTEMPTS: "2"

  # Optional delay before triggering the re-run (seconds).
  # Useful if failures are due to transient infra glitches.
  BACKOFF_SECONDS: "360"

jobs:
  rerun-full-on-failure:
    # Only proceed if the target workflow concluded as failure and we
    # haven't exceeded the allowed attempts.
    if: >
      ${{
        github.event.workflow_run.conclusion == 'failure' &&
        github.event.workflow_run.run_attempt < env.MAX_ATTEMPTS
      }}
    runs-on: ubuntu-latest

    steps:
      - name: Show context
        run: |
          echo "Target workflow:    ${{ github.event.workflow.name }}"
          echo "Failed run ID:      ${{ github.event.workflow_run.id }}"
          echo "Attempt number:     ${{ github.event.workflow_run.run_attempt }}"
          echo "Conclusion:         ${{ github.event.workflow_run.conclusion }}"
          echo "Max attempts:       ${MAX_ATTEMPTS}"
          echo "Backoff (seconds):  ${BACKOFF_SECONDS}"

      - name: Optional backoff
        if: ${{ env.BACKOFF_SECONDS != '0' }}
        run: sleep "${BACKOFF_SECONDS}"

      - name: Re-run entire workflow run via API
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = context.payload.workflow_run.id;
            const { owner, repo } = context.repo;

            // POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun
            await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
              owner, repo, run_id
            });
            core.info(`Triggered full re-run for run ${run_id}.`);

